<a href="https://colab.research.google.com/github/divyamehra17/Resume/blob/main/icbms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cleaning and preparing the data for model training

In [9]:
#importing the libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline



In [10]:
#importing the dataset
df=pd.read_csv('/content/skeleton_filtered.csv',encoding='latin-1')
df.head()


nose_x    nose_y    neck_x  neck_y  ...    REar_y    LEar_x    LEar_y  class
0  0.643519  0.157609  0.634259    0.25  ...  0.157609  0.666667  0.152174   kick
1  0.643519  0.157609  0.634259    0.25  ...  0.157609  0.666667  0.152174   kick
2  0.643519  0.157609  0.638889    0.25  ...  0.157609  0.671296  0.152174   kick
3  0.643519  0.157609  0.638889    0.25  ...  0.157609  0.666667  0.152174   kick
4  0.643519  0.157609  0.638889    0.25  ...  0.157609  0.666667  0.152174   kick

[5 rows x 37 columns]

In [11]:
df.columns

Index(['nose_x', 'nose_y', 'neck_x', 'neck_y', 'Rshoulder_x', 'Rshoulder_y',
       'Relbow_x', 'Relbow_y', 'Rwrist_x', 'RWrist_y', 'LShoulder_x',
       'LShoulder_y', 'LElbow_x', 'LElbow_y', 'LWrist_x', 'LWrist_y', 'RHip_x',
       'RHip_y', 'RKnee_x', 'RKnee_y', 'RAnkle_x', 'RAnkle_y', 'LHip_x',
       'LHip_y', 'LKnee_x', 'LKnee_y', 'LAnkle_x', 'LAnkle_y', 'REye_x',
       'REye_y', 'LEye_x', 'LEye_y', 'REar_x', 'REar_y', 'LEar_x', 'LEar_y',
       'class'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1584 entries, 0 to 1583
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   nose_x       1584 non-null   float64
 1   nose_y       1584 non-null   float64
 2   neck_x       1584 non-null   float64
 3   neck_y       1584 non-null   float64
 4   Rshoulder_x  1584 non-null   float64
 5   Rshoulder_y  1584 non-null   float64
 6   Relbow_x     1584 non-null   float64
 7   Relbow_y     1584 non-null   float64
 8   Rwrist_x     1584 non-null   float64
 9   RWrist_y     1583 non-null   float64
 10  LShoulder_x  1583 non-null   float64
 11  LShoulder_y  1583 non-null   float64
 12  LElbow_x     1583 non-null   float64
 13  LElbow_y     1583 non-null   float64
 14  LWrist_x     1583 non-null   float64
 15  LWrist_y     1583 non-null   float64
 16  RHip_x       1583 non-null   float64
 17  RHip_y       1583 non-null   float64
 18  RKnee_x      1583 non-null   float64
 19  RKnee_

In [13]:
df.describe()

nose_x       nose_y  ...       LEar_x       LEar_y
count  1584.000000  1584.000000  ...  1583.000000  1583.000000
mean      0.586645     0.312263  ...     0.484342     0.238609
std       0.052490     0.140211  ...     0.250453     0.172137
min       0.453704     0.125000  ...     0.000000     0.000000
25%       0.550926     0.163043  ...     0.537037     0.141304
50%       0.578704     0.336957  ...     0.597222     0.163043
75%       0.620370     0.467391  ...     0.629630     0.440217
max       0.731481     0.548913  ...     0.745370     0.516304

[8 rows x 36 columns]



In Data Analysis What All Things We Do

    Missing Values
    Explore About the Numerical Variables
    Explore About categorical Variables
    Finding Relationship between features


```
# This is formatted as code
```



In [15]:
df.shape

(1584, 37)

In [16]:


df.isnull().sum()



nose_x         0
nose_y         0
neck_x         0
neck_y         0
Rshoulder_x    0
Rshoulder_y    0
Relbow_x       0
Relbow_y       0
Rwrist_x       0
RWrist_y       1
LShoulder_x    1
LShoulder_y    1
LElbow_x       1
LElbow_y       1
LWrist_x       1
LWrist_y       1
RHip_x         1
RHip_y         1
RKnee_x        1
RKnee_y        1
RAnkle_x       1
RAnkle_y       1
LHip_x         1
LHip_y         1
LKnee_x        1
LKnee_y        1
LAnkle_x       1
LAnkle_y       1
REye_x         1
REye_y         1
LEye_x         1
LEye_y         1
REar_x         1
REar_y         1
LEar_x         1
LEar_y         1
class          1
dtype: int64

In [17]:
## Focus on replacing missing values
df['RWrist_y'].unique()



array([0.43478261, 0.42934783, 0.42391304, 0.41847826, 0.4076087 ,
       0.39130435, 0.40217391, 0.41304348, 0.44021739, 0.45652174,
       0.46195652, 0.35869565, 0.39673913, 0.375     , 0.47826087,
       0.4673913 , 0.47282609, 0.44565217, 0.45108696, 0.48369565,
       0.48913043, 0.49456522, 0.5       , 0.36413043, 0.36956522,
       0.38043478, 0.38586957, 0.33695652, 0.53804348, 0.5326087 ,
       0.52717391, 0.54347826, 0.55434783, 0.54891304, 0.61413043,
       0.61956522, 0.60869565, 0.59782609, 0.58152174, 0.5923913 ,
       0.58695652, 0.57065217, 0.60326087, 0.625     , 0.63043478,
       0.57608696, 0.55978261, 0.64130435, 0.63586957, 0.56521739,
       0.50543478, 0.51086957, 0.52173913, 0.51630435, 0.19565217,
       0.19021739, 0.20108696, 0.20652174, 0.22282609, 0.2173913 ,
       0.21195652, 0.22826087, 0.23369565, 0.23913043, 0.24456522,
       0.25543478, 0.25      , 0.26630435, 0.2826087 , 0.28804348,
       0.29347826, 0.29891304, 0.30434783, 0.30978261, 0.31521

In [18]:
df['RWrist_y'].value_counts()


0.228261    69
0.222826    44
0.451087    39
0.217391    38
0.543478    36
            ..
0.358696     1
0.342391     1
0.255435     1
0.820652     1
0.266304     1
Name: RWrist_y, Length: 111, dtype: int64

In [19]:
df['RWrist_y'].mode()[0]

0.2282608695652173

In [20]:
## Replace the missing values with mode
df['RWrist_y']=df['RWrist_y'].fillna(df['RWrist_y'].mode()[0])


In [21]:
df['RWrist_y'].isnull().sum()


0

In [22]:
df['LShoulder_x'].unique()

array([0.68055556, 0.68518519, 0.67592593, 0.69444444, 0.69907407,
       0.7037037 , 0.71296296, 0.72685185, 0.73148148, 0.73611111,
       0.74537037, 0.74074074, 0.72222222, 0.63888889, 0.64351852,
       0.66203704, 0.70833333, 0.71759259, 0.75      , 0.75462963,
       0.66666667, 0.68981481, 0.61574074, 0.62037037, 0.625     ,
       0.63425926, 0.61111111, 0.60185185, 0.59259259, 0.58796296,
       0.58333333, 0.5787037 , 0.57407407, 0.56944444, 0.56481481,
       0.56018519, 0.59722222, 0.60648148, 0.62962963, 0.64814815,
       0.65277778, 0.65740741, 0.6712963 , 0.5462963 , 0.55092593,
       0.55555556, 0.54166667, 0.53703704, 0.52314815, 0.51388889,
       0.50925926, 0.51851852, 0.52777778, 0.53240741,        nan])

In [23]:
df['LShoulder_x'].value_counts()


0.634259    82
0.643519    79
0.648148    76
0.625000    76
0.606481    73
0.629630    68
0.601852    67
0.615741    61
0.638889    61
0.611111    56
0.657407    55
0.675926    53
0.620370    47
0.652778    45
0.662037    43
0.680556    41
0.597222    39
0.583333    38
0.578704    37
0.587963    37
0.592593    36
0.666667    34
0.685185    28
0.671296    26
0.699074    24
0.574074    24
0.703704    23
0.689815    22
0.708333    20
0.694444    19
0.569444    18
0.564815    17
0.555556    15
0.736111    15
0.712963    14
0.560185    13
0.731481    12
0.546296    12
0.717593    11
0.550926    10
0.722222     9
0.726852     9
0.745370     8
0.541667     8
0.740741     7
0.537037     3
0.513889     2
0.527778     2
0.509259     2
0.750000     2
0.523148     1
0.518519     1
0.754630     1
0.532407     1
Name: LShoulder_x, dtype: int64

In [24]:
df['LShoulder_x'].mode()[0]

0.6342592592592593

In [25]:
df['LShoulder_x']=df['LShoulder_x'].fillna(df['LShoulder_x'].mode()[0])


In [26]:
df['LShoulder_x'].isnull().sum()

0

In [27]:
df['LShoulder_y'].unique()

array([0.25543478, 0.25      , 0.26630435, 0.26086957, 0.27717391,
       0.2826087 , 0.27173913, 0.24456522, 0.28804348, 0.23913043,
       0.21195652, 0.2173913 , 0.23369565, 0.22282609, 0.22826087,
       0.20108696, 0.29347826, 0.30434783, 0.30978261, 0.20652174,
       0.42934783, 0.43478261, 0.41304348, 0.41847826, 0.42391304,
       0.4076087 , 0.40217391, 0.38586957, 0.39130435, 0.39673913,
       0.38043478, 0.36956522, 0.375     , 0.44021739, 0.44565217,
       0.45108696, 0.47826087, 0.48369565, 0.48913043, 0.47282609,
       0.4673913 , 0.49456522, 0.5       , 0.51086957, 0.52173913,
       0.52717391, 0.5326087 , 0.51630435, 0.50543478, 0.53804348,
       0.54347826, 0.54891304, 0.55434783, 0.55978261, 0.56521739,
       0.57065217, 0.57608696,        nan])

In [28]:
df['LShoulder_y'].value_counts()


0.233696    141
0.239130    110
0.228261    103
0.222826     70
0.244565     68
0.418478     63
0.489130     63
0.543478     61
0.423913     58
0.538043     52
0.217391     51
0.510870     47
0.532609     37
0.527174     36
0.402174     36
0.516304     35
0.521739     33
0.548913     32
0.554348     32
0.407609     29
0.500000     28
0.396739     27
0.505435     27
0.211957     25
0.413043     25
0.391304     24
0.559783     23
0.255435     19
0.429348     17
0.565217     17
0.385870     17
0.266304     16
0.494565     15
0.250000     14
0.260870     12
0.277174     12
0.380435     11
0.293478     11
0.478261     10
0.271739     10
0.483696      9
0.206522      8
0.282609      7
0.288043      7
0.570652      6
0.434783      5
0.472826      4
0.375000      4
0.576087      3
0.369565      3
0.304348      2
0.451087      2
0.440217      2
0.201087      1
0.309783      1
0.467391      1
0.445652      1
Name: LShoulder_y, dtype: int64

In [29]:
df['LShoulder_y'].mode()[0]

0.233695652173913

In [30]:
df['LShoulder_y']=df['LShoulder_y'].fillna(df['LShoulder_y'].mode()[0])


In [31]:
df['LShoulder_y'].isnull().sum()

0

In [32]:
df['LElbow_x'].unique()

array([0.68518519, 0.68981481, 0.68055556, 0.67592593, 0.69907407,
       0.7037037 , 0.70833333, 0.71759259, 0.73148148, 0.73611111,
       0.74074074, 0.75      , 0.75925926, 0.76388889, 0.75462963,
       0.74537037, 0.71296296, 0.64351852, 0.65277778, 0.72222222,
       0.72685185, 0.66203704, 0.6712963 , 0.63888889, 0.64814815,
       0.65740741, 0.66666667, 0.625     , 0.62037037, 0.61574074,
       0.61111111, 0.60648148, 0.60185185, 0.58796296, 0.5787037 ,
       0.57407407, 0.56944444, 0.58333333, 0.59722222, 0.62962963,
       0.63425926, 0.69444444, 0.77314815, 0.79166667, 0.78240741,
       0.59259259, 0.56481481, 0.56018519, 0.55555556, 0.5462963 ,
       0.53703704, 0.53240741, 0.52777778, 0.54166667, 0.55092593,
       0.52314815, 0.51851852, 0.5       ,        nan])

In [33]:
df['LElbow_x'].value_counts()

0.662037    84
0.643519    68
0.680556    65
0.657407    63
0.671296    63
0.685185    62
0.689815    62
0.666667    56
0.648148    56
0.694444    54
0.726852    53
0.638889    52
0.629630    44
0.712963    43
0.634259    42
0.652778    41
0.703704    39
0.699074    38
0.708333    34
0.620370    33
0.722222    33
0.625000    32
0.675926    32
0.731481    32
0.717593    28
0.736111    26
0.615741    25
0.597222    24
0.611111    24
0.601852    24
0.574074    23
0.606481    22
0.587963    20
0.740741    19
0.592593    18
0.578704    17
0.745370    16
0.750000    16
0.583333    12
0.569444    11
0.754630    10
0.759259     9
0.564815     7
0.532407     7
0.555556     6
0.546296     5
0.550926     5
0.541667     4
0.560185     4
0.537037     4
0.518519     3
0.763889     3
0.523148     2
0.773148     2
0.527778     2
0.782407     2
0.791667     1
0.500000     1
Name: LElbow_x, dtype: int64

In [34]:
df['LElbow_x'].mode()[0]

0.6620370370370371

In [35]:
df['LElbow_x']=df['LElbow_x'].fillna(df['LElbow_x'].mode()[0])


In [36]:
df['LElbow_x'].isnull().sum()

0

In [37]:
df['LElbow_y'].unique()

array([0.35869565, 0.35326087, 0.36956522, 0.36413043, 0.38586957,
       0.38043478, 0.375     , 0.34782609, 0.39130435, 0.32608696,
       0.33152174, 0.33695652, 0.30434783, 0.32065217, 0.3423913 ,
       0.30978261, 0.31521739, 0.29347826, 0.39673913, 0.28804348,
       0.29891304, 0.50543478, 0.51086957, 0.51630435, 0.52173913,
       0.52717391, 0.49456522, 0.5       , 0.48913043, 0.48369565,
       0.47282609, 0.47826087, 0.4673913 , 0.45652174, 0.45108696,
       0.46195652, 0.44565217, 0.44021739, 0.42934783, 0.5326087 ,
       0.53804348, 0.54891304, 0.54347826, 0.22826087, 0.26630435,
       0.23369565, 0.2173913 , 0.21195652, 0.22282609, 0.23913043,
       0.24456522, 0.26086957, 0.25543478, 0.27173913, 0.25      ,
       0.20652174, 0.27717391, 0.55434783, 0.55978261, 0.56521739,
       0.57065217, 0.57608696, 0.58152174, 0.59782609, 0.60869565,
       0.61413043, 0.625     , 0.61956522, 0.60326087, 0.5923913 ,
       0.58695652, 0.63043478, 0.64130435, 0.64673913, 0.65217

In [38]:
df['LElbow_y'].value_counts()

0.342391    64
0.353261    59
0.347826    55
0.510870    52
0.358696    47
            ..
0.440217     2
0.293478     2
0.396739     1
0.206522     1
0.429348     1
Name: LElbow_y, Length: 86, dtype: int64

In [39]:
df['LElbow_y'].mode()[0]

0.3423913043478261

In [40]:
df['LElbow_y']=df['LElbow_y'].fillna(df['LElbow_y'].mode()[0])


In [41]:
df['LElbow_y'].isnull().sum()

0

In [42]:
df['LWrist_x'].unique()

array([0.67592593, 0.68518519, 0.69444444, 0.68981481, 0.68055556,
       0.6712963 , 0.69907407, 0.70833333, 0.71296296, 0.71759259,
       0.72685185, 0.73611111, 0.74074074, 0.73148148, 0.72222222,
       0.7037037 , 0.65740741, 0.66203704, 0.64814815, 0.64351852,
       0.63888889, 0.63425926, 0.62962963, 0.62037037, 0.60185185,
       0.59259259, 0.59722222, 0.60648148, 0.61111111, 0.61574074,
       0.625     , 0.65277778, 0.66666667, 0.75      , 0.75925926,
       0.76388889, 0.76851852, 0.5787037 , 0.58333333, 0.58796296,
       0.57407407, 0.77777778, 0.77314815, 0.75462963, 0.74537037,
       0.78703704, 0.79166667, 0.78240741, 0.56944444, 0.56481481,
       0.55555556, 0.55092593, 0.5462963 , 0.53703704, 0.53240741,
       0.52777778, 0.54166667, 0.4537037 , 0.46296296, 0.45833333,
       0.46759259, 0.47222222, 0.48611111, 0.5       , 0.51851852,
       0.51388889, 0.49537037, 0.50462963, 0.50925926, 0.52314815,
       0.48148148, 0.44907407, 0.44444444, 0.43981481, 0.56018

In [43]:
df['LWrist_x'].value_counts()

0.657407    84
0.662037    77
0.675926    68
0.643519    66
0.689815    65
            ..
0.523148     1
0.782407     1
0.787037     1
0.476852     1
0.791667     1
Name: LWrist_x, Length: 78, dtype: int64

In [44]:
df['LWrist_x'].mode()[0]

0.6574074074074074

In [45]:
df['LWrist_x']=df['LWrist_x'].fillna(df['LWrist_x'].mode()[0])


In [46]:
df['LWrist_x'].isnull().sum()

0

In [47]:
df['LWrist_y'].unique()

array([0.44021739, 0.42934783, 0.42391304, 0.43478261, 0.45108696,
       0.44565217, 0.46195652, 0.4673913 , 0.41847826, 0.39673913,
       0.41304348, 0.45652174, 0.4076087 , 0.38586957, 0.38043478,
       0.39130435, 0.40217391, 0.375     , 0.36413043, 0.34782609,
       0.36956522, 0.56521739, 0.57608696, 0.58695652, 0.58152174,
       0.5923913 , 0.59782609, 0.60326087, 0.57065217, 0.55978261,
       0.55434783, 0.54891304, 0.54347826, 0.5326087 , 0.53804348,
       0.52717391, 0.51630435, 0.60869565, 0.61956522, 0.61413043,
       0.625     , 0.63043478, 0.22826087, 0.29347826, 0.23913043,
       0.22282609, 0.21195652, 0.2173913 , 0.20652174, 0.20108696,
       0.19565217, 0.23369565, 0.24456522, 0.19021739, 0.25      ,
       0.26086957, 0.27717391, 0.2826087 , 0.30434783, 0.29891304,
       0.28804348, 0.30978261, 0.31521739, 0.25543478, 0.64130435,
       0.63586957, 0.64673913, 0.65217391, 0.66304348, 0.68478261,
       0.69565217, 0.71195652, 0.7173913 , 0.72282609, 0.70652

In [48]:
df['LWrist_y'].value_counts()

0.451087    63
0.445652    48
0.440217    42
0.597826    41
0.239130    37
            ..
0.260870     1
0.809783     1
0.804348     1
0.516304     1
0.369565     1
Name: LWrist_y, Length: 103, dtype: int64

In [49]:
df['LWrist_y'].mode()[0]

0.4510869565217391

In [51]:
df['LWrist_y']=df['LWrist_y'].fillna(df['LWrist_y'].mode()[0])

In [52]:
df['LWrist_y'].isnull().sum()

0

In [53]:
df['RHip_x'].unique()

array([0.58796296, 0.59259259, 0.59722222, 0.60185185, 0.61111111,
       0.60648148, 0.61574074, 0.62037037, 0.625     , 0.62962963,
       0.63425926, 0.63888889, 0.64351852, 0.64814815, 0.57407407,
       0.56944444, 0.56481481, 0.56018519, 0.55555556, 0.55092593,
       0.5462963 , 0.54166667, 0.53703704, 0.53240741, 0.52777778,
       0.52314815, 0.51851852, 0.5787037 , 0.68055556, 0.67592593,
       0.6712963 , 0.66203704, 0.65277778, 0.50925926, 0.50462963,
       0.51388889, 0.58333333, 0.5       , 0.49537037, 0.49074074,
       0.48611111, 0.47685185, 0.47222222, 0.46759259, 0.45833333,
       0.44907407, 0.44444444, 0.43981481, 0.43518519, 0.43055556,
       0.48148148,        nan])

In [54]:
df['RHip_x'].value_counts()

0.555556    113
0.569444    111
0.550926     96
0.560185     88
0.546296     87
0.523148     75
0.564815     75
0.574074     74
0.578704     66
0.597222     62
0.601852     60
0.532407     60
0.527778     59
0.583333     57
0.592593     56
0.541667     51
0.587963     50
0.537037     48
0.518519     40
0.513889     37
0.504630     32
0.509259     28
0.611111     23
0.606481     19
0.615741     16
0.500000     10
0.634259      9
0.629630      8
0.625000      8
0.620370      6
0.490741      6
0.638889      5
0.495370      5
0.472222      5
0.675926      4
0.476852      4
0.430556      4
0.486111      4
0.643519      3
0.467593      3
0.458333      3
0.449074      2
0.439815      2
0.671296      2
0.444444      1
0.435185      1
0.648148      1
0.652778      1
0.662037      1
0.680556      1
0.481481      1
Name: RHip_x, dtype: int64

In [55]:
df['RHip_x'].mode()[0]

0.5555555555555556

In [56]:
df['RHip_x']=df['RHip_x'].fillna(df['RHip_x'].mode()[0])

In [57]:
df['RHip_x'].isnull().sum()

0

In [58]:
df['RHip_y'].unique()

array([0.43478261, 0.42934783, 0.44021739, 0.41304348, 0.44565217,
       0.42391304, 0.41847826, 0.40217391, 0.39673913, 0.4076087 ,
       0.45652174, 0.45108696, 0.46195652, 0.47282609, 0.47826087,
       0.4673913 , 0.48369565, 0.39130435, 0.375     , 0.56521739,
       0.55978261, 0.55434783, 0.57065217, 0.57608696, 0.60326087,
       0.59782609, 0.5923913 , 0.58695652, 0.58152174, 0.60869565,
       0.61413043, 0.61956522, 0.625     , 0.6576087 , 0.66304348,
       0.66847826, 0.67391304, 0.67934783, 0.65217391, 0.64673913,
       0.64130435, 0.63586957, 0.63043478, 0.68478261, 0.69021739,
       0.69565217, 0.70108696, 0.70652174, 0.71195652, 0.7173913 ,
       0.72282609, 0.72826087, 0.73369565, 0.73913043, 0.74456522,
       0.75      , 0.75543478, 0.77173913, 0.76630435, 0.79347826,
       0.78804348, 0.7826087 , 0.77717391, 0.76086957,        nan])

In [59]:
df['RHip_y'].value_counts()

0.456522    153
0.451087    132
0.445652    101
0.440217     63
0.673913     58
           ... 
0.717391      2
0.728261      1
0.793478      1
0.375000      1
0.391304      1
Name: RHip_y, Length: 64, dtype: int64

In [60]:
df['RHip_y'].mode()[0]

0.4565217391304347

In [61]:
df['RHip_y']=df['RHip_y'].fillna(df['RHip_y'].mode()[0])

In [62]:
df['RHip_y'].isnull().sum()

0

In [63]:
df['RKnee_x'].unique()

array([0.58796296, 0.59259259, 0.59722222, 0.60185185, 0.61574074,
       0.62962963, 0.63425926, 0.58333333, 0.57407407, 0.56481481,
       0.55555556, 0.55092593, 0.56018519, 0.5787037 , 0.61111111,
       0.65740741, 0.68055556, 0.68981481, 0.71759259, 0.72222222,
       0.76851852, 0.75925926, 0.74537037, 0.64814815, 0.5462963 ,
       0.54166667, 0.53240741, 0.52314815, 0.53703704, 0.62037037,
       0.68518519, 0.70833333, 0.74074074, 0.73611111, 0.72685185,
       0.69907407, 0.6712963 , 0.65277778, 0.64351852, 0.60648148,
       0.56944444, 0.52777778, 0.51851852, 0.66203704, 0.66666667,
       0.69444444, 0.625     , 0.63888889, 0.67592593, 0.51388889,
       0.50925926, 0.5       , 0.49074074, 0.48611111, 0.49537037,
       0.50462963, 0.7037037 , 0.71296296, 0.48148148, 0.46759259,
       0.46296296, 0.44907407, 0.44444444, 0.43981481, 0.43055556,
       0.43518519, 0.4537037 , 0.47222222, 0.47685185, 0.45833333,
       0.42592593, 0.4212963 , 0.41666667,        nan])

In [64]:
df['RKnee_x'].value_counts()

0.518519    72
0.527778    67
0.523148    63
0.532407    63
0.513889    62
            ..
0.759259     1
0.745370     1
0.712963     1
0.740741     1
0.736111     1
Name: RKnee_x, Length: 73, dtype: int64

In [65]:
df['RKnee_x'].mode()[0]

0.5185185185185185

In [66]:
df['RKnee_x']=df['RKnee_x'].fillna(df['RKnee_x'].mode()[0])

In [67]:
df['RKnee_x'].isnull().sum()

0

In [68]:
df['RKnee_y'].unique()

array([0.57608696, 0.57065217, 0.58152174, 0.59782609, 0.60326087,
       0.5923913 , 0.58695652, 0.54891304, 0.56521739, 0.5326087 ,
       0.53804348, 0.52717391, 0.55978261, 0.55434783, 0.45108696,
       0.4673913 , 0.46195652, 0.51630435, 0.51086957, 0.47826087,
       0.41304348, 0.48369565, 0.50543478, 0.625     , 0.61413043,
       0.60869565, 0.61956522, 0.63586957, 0.64673913, 0.64130435,
       0.63043478, 0.6576087 , 0.65217391, 0.5       , 0.49456522,
       0.40217391, 0.38586957, 0.38043478, 0.375     , 0.4076087 ,
       0.44565217, 0.35326087, 0.42934783, 0.66847826, 0.67391304,
       0.69021739, 0.68478261, 0.67934783, 0.70108696, 0.70652174,
       0.66304348, 0.69565217, 0.7173913 , 0.71195652, 0.75      ,
       0.75543478, 0.74456522, 0.72826087, 0.73369565, 0.72282609,
       0.76630435, 0.76086957, 0.77173913, 0.77717391, 0.7826087 ,
       0.73913043, 0.78804348, 0.79347826, 0.79891304, 0.80978261,
       0.81521739, 0.82065217, 0.82608696, 0.83152174, 0.80434

In [69]:
df['RKnee_y'].value_counts()

0.619565    94
0.614130    77
0.625000    75
0.608696    70
0.603261    59
            ..
0.467391     1
0.918478     1
0.445652     1
0.353261     1
0.429348     1
Name: RKnee_y, Length: 93, dtype: int64

In [70]:
df['RKnee_y'].mode()[0]

0.6195652173913043

In [71]:
df['RKnee_y']=df['RKnee_y'].fillna(df['RKnee_y'].mode()[0])

In [72]:
df['RKnee_y'].isnull().sum()

0

In [73]:
df['RAnkle_x'].unique()

array([0.58796296, 0.58333333, 0.59722222, 0.60185185, 0.625     ,
       0.65277778, 0.6712963 , 0.5787037 , 0.56481481, 0.5462963 ,
       0.52314815, 0.51388889, 0.50462963, 0.49537037, 0.49074074,
       0.50925926, 0.52777778, 0.56018519, 0.61574074, 0.65740741,
       0.70833333, 0.75462963, 0.84259259, 0.82407407, 0.7962963 ,
       0.64814815, 0.61111111, 0.48611111, 0.47685185, 0.45833333,
       0.44444444, 0.51851852, 0.69907407, 0.75      , 0.77777778,
       0.81481481, 0.80555556, 0.76388889, 0.74074074, 0.68981481,
       0.62962963, 0.57407407, 0.53703704, 0.60648148, 0.59259259,
       0.55555556, 0.56944444, 0.63888889, 0.64351852, 0.55092593,
       0.5       , 0.48148148, 0.62037037, 0.7037037 , 0.54166667,
       0.47222222, 0.46296296, 0.43055556, 0.41666667, 0.4212963 ,
       0.43518519, 0.44907407, 0.69444444, 0.72222222, 0.66666667,
       0.66203704, 0.53240741, 0.4537037 , 0.43981481, 0.46759259,
       0.67592593, 0.68518519, 0.42592593, 0.63425926, 0.68055

In [74]:
df['RAnkle_x'].value_counts()

0.560185    115
0.555556     86
0.564815     81
0.546296     75
0.518519     71
           ... 
0.814815      1
0.634259      1
0.421296      1
0.694444      1
0.787037      1
Name: RAnkle_x, Length: 87, dtype: int64

In [75]:
df['RAnkle_x'].mode()[0]

0.5601851851851852

In [76]:
df['RAnkle_x']=df['RAnkle_x'].fillna(df['RAnkle_x'].mode()[0])

In [77]:
df['RAnkle_x'].isnull().sum()

0

In [78]:
df['RAnkle_y'].unique()

array([0.74456522, 0.73913043, 0.75543478, 0.75      , 0.76086957,
       0.72826087, 0.71195652, 0.67934783, 0.69021739, 0.67391304,
       0.70652174, 0.73369565, 0.56521739, 0.625     , 0.64673913,
       0.66847826, 0.77173913, 0.63586957, 0.65217391, 0.6576087 ,
       0.60326087, 0.55978261, 0.66304348, 0.68478261, 0.70108696,
       0.77717391, 0.78804348, 0.7826087 , 0.79347826, 0.79891304,
       0.80434783, 0.80978261, 0.82608696, 0.83152174, 0.63043478,
       0.60869565, 0.53804348, 0.59782609, 0.64130435, 0.52717391,
       0.47826087, 0.45652174, 0.51086957, 0.57065217, 0.58695652,
       0.61956522, 0.50543478, 0.52173913, 0.54347826, 0.76630435,
       0.81521739, 0.82065217, 0.84782609, 0.83695652, 0.85326087,
       0.8423913 , 0.88586957, 0.85869565, 0.9076087 , 0.90217391,
       0.91304348, 0.89673913, 0.86413043, 0.91847826, 0.92391304,
       0.95652174, 0.96195652, 0.95108696, 0.94021739, 0.94565217,
       0.93478261, 0.88043478, 0.9673913 , 0.92934783, 0.89130

In [79]:
df['RAnkle_y'].value_counts()

0.760870    118
0.766304    102
0.777174     92
0.782609     77
0.788043     69
           ... 
0.510870      1
0.570652      1
0.619565      1
0.505435      1
0.478261      1
Name: RAnkle_y, Length: 80, dtype: int64

In [80]:
df['RAnkle_y'].mode()[0]

0.7608695652173914

In [81]:
df['RAnkle_y']=df['RAnkle_y'].fillna(df['RAnkle_y'].mode()[0])

In [82]:
df['RAnkle_y'].isnull().sum()

0

In [83]:
df['LHip_x'].unique()

array([0.64814815, 0.65277778, 0.65740741, 0.66203704, 0.66666667,
       0.67592593, 0.6712963 , 0.68055556, 0.68518519, 0.68981481,
       0.69444444, 0.69907407, 0.63888889, 0.62962963, 0.64351852,
       0.63425926, 0.625     , 0.62037037, 0.61574074, 0.61111111,
       0.60648148, 0.60185185, 0.59722222, 0.59259259, 0.58796296,
       0.58333333, 0.5787037 , 0.56944444, 0.57407407, 0.56481481,
       0.74074074, 0.73148148, 0.72685185, 0.72222222, 0.7037037 ,
       0.56018519, 0.55555556, 0.55092593, 0.54166667, 0.53703704,
       0.53240741, 0.52777778, 0.52314815, 0.51851852, 0.51388889,
       0.50925926, 0.5       , 0.50462963,        nan])

In [84]:
df['LHip_x'].value_counts()

0.606481    126
0.611111    116
0.629630    110
0.601852     97
0.625000     80
0.620370     78
0.643519     77
0.662037     71
0.615741     71
0.587963     64
0.638889     63
0.583333     61
0.634259     60
0.597222     51
0.592593     49
0.648148     45
0.578704     44
0.652778     44
0.666667     42
0.657407     35
0.574074     34
0.564815     27
0.569444     21
0.671296     18
0.560185     13
0.555556     12
0.675926      7
0.680556      6
0.685185      6
0.689815      6
0.541667      6
0.694444      6
0.500000      5
0.513889      5
0.740741      4
0.550926      4
0.518519      3
0.509259      2
0.523148      2
0.699074      2
0.726852      2
0.532407      2
0.527778      1
0.537037      1
0.703704      1
0.722222      1
0.731481      1
0.504630      1
Name: LHip_x, dtype: int64

In [85]:
df['LHip_x'].mode()[0]

0.6064814814814815

In [86]:
df['LHip_x']=df['LHip_x'].fillna(df['LHip_x'].mode()[0])

In [87]:
df['LHip_x'].isnull().sum()

0

In [88]:
df['LHip_y'].unique()

array([0.44565217, 0.44021739, 0.46195652, 0.45652174, 0.4673913 ,
       0.45108696, 0.42934783, 0.42391304, 0.43478261, 0.41847826,
       0.41304348, 0.40217391, 0.4076087 , 0.57065217, 0.57608696,
       0.56521739, 0.58152174, 0.58695652, 0.5923913 , 0.59782609,
       0.60326087, 0.55978261, 0.55434783, 0.60869565, 0.61413043,
       0.61956522, 0.63586957, 0.625     , 0.63043478, 0.47282609,
       0.47826087, 0.48369565, 0.65217391, 0.6576087 , 0.66304348,
       0.64673913, 0.64130435, 0.66847826, 0.67391304, 0.67934783,
       0.69565217, 0.70108696, 0.70652174, 0.71195652, 0.69021739,
       0.68478261, 0.7173913 , 0.72282609, 0.72826087, 0.73369565,
       0.73913043, 0.74456522, 0.75      , 0.75543478, 0.76086957,
       0.76630435, 0.77173913, 0.7826087 , 0.77717391, 0.78804348,
       0.79347826, 0.79891304,        nan])

In [89]:
df['LHip_y'].value_counts()

0.445652    120
0.451087    103
0.461957     90
0.456522     90
0.440217     78
           ... 
0.793478      3
0.559783      2
0.407609      2
0.554348      1
0.798913      1
Name: LHip_y, Length: 62, dtype: int64

In [90]:
df['LHip_y'].mode()[0]

0.4456521739130434

In [93]:
df['LHip_y']=df['LHip_y'].fillna(df['LHip_y'].mode()[0])

In [94]:
df['LHip_y'].isnull().sum()

0

In [95]:
df['LKnee_x'].unique()

array([0.63425926, 0.63888889, 0.64351852, 0.64814815, 0.65277778,
       0.65740741, 0.66666667, 0.66203704, 0.6712963 , 0.67592593,
       0.68055556, 0.68981481, 0.71296296, 0.69907407, 0.69444444,
       0.62037037, 0.60648148, 0.57407407, 0.56481481, 0.5462963 ,
       0.58796296, 0.68518519, 0.61111111, 0.55555556, 0.52314815,
       0.51851852, 0.49074074, 0.48148148, 0.47685185, 0.47222222,
       0.5       , 0.50462963, 0.53703704, 0.56018519, 0.70833333,
       0.73148148, 0.75925926, 0.77314815, 0.78703704, 0.72222222,
       0.7037037 , 0.625     , 0.56944444, 0.72685185, 0.78240741,
       0.81018519, 0.7962963 , 0.79166667, 0.76388889, 0.59722222,
       0.58333333, 0.60185185, 0.59259259, 0.61574074, 0.5787037 ,
       0.48611111, 0.62962963, 0.55092593, 0.52777778, 0.51388889,
       0.54166667, 0.50925926, 0.49537037, 0.53240741, 0.73611111,
       0.74074074, 0.74537037, 0.75      , 0.71759259,        nan])

In [96]:
df['LKnee_x'].value_counts()

0.601852    78
0.611111    69
0.597222    67
0.606481    64
0.694444    59
            ..
0.796296     1
0.810185     1
0.782407     1
0.787037     1
0.717593     1
Name: LKnee_x, Length: 69, dtype: int64

In [97]:
df['LKnee_x'].mode()[0]

0.6018518518518519

In [98]:
df['LKnee_x']=df['LKnee_x'].fillna(df['LKnee_x'].mode()[0])

In [99]:
df['LKnee_x'].isnull().sum()

0

In [100]:
df['LKnee_y'].unique()

array([0.59782609, 0.5923913 , 0.58695652, 0.60326087, 0.61956522,
       0.61413043, 0.60869565, 0.57608696, 0.57065217, 0.56521739,
       0.625     , 0.58152174, 0.55434783, 0.55978261, 0.48913043,
       0.5       , 0.51086957, 0.5326087 , 0.54891304, 0.54347826,
       0.47826087, 0.52717391, 0.51630435, 0.52173913, 0.50543478,
       0.53804348, 0.4673913 , 0.45652174, 0.45108696, 0.43478261,
       0.46195652, 0.47282609, 0.44565217, 0.42934783, 0.70108696,
       0.73913043, 0.7173913 , 0.66304348, 0.66847826, 0.68478261,
       0.72282609, 0.73369565, 0.74456522, 0.75      , 0.72826087,
       0.67934783, 0.70652174, 0.71195652, 0.69565217, 0.69021739,
       0.63586957, 0.64673913, 0.65217391, 0.6576087 , 0.67391304,
       0.64130435, 0.75543478, 0.77173913, 0.77717391, 0.79347826,
       0.78804348, 0.76630435, 0.7826087 , 0.76086957, 0.79891304,
       0.63043478, 0.80434783, 0.80978261, 0.82608696, 0.83152174,
       0.8423913 , 0.84782609, 0.83695652, 0.82065217, 0.81521

In [101]:
df['LKnee_y'].value_counts()

0.614130    75
0.608696    72
0.619565    69
0.625000    57
0.597826    54
            ..
0.445652     2
0.489130     1
0.923913     1
0.478261     1
0.880435     1
Name: LKnee_y, Length: 85, dtype: int64

In [102]:
df['LKnee_y'].mode()[0]

0.6141304347826086

In [103]:
df['LKnee_y']=df['LKnee_y'].fillna(df['LKnee_y'].mode()[0])

In [104]:
df['LKnee_y'].isnull().sum()

0

In [105]:
df.isnull().sum()

nose_x         0
nose_y         0
neck_x         0
neck_y         0
Rshoulder_x    0
Rshoulder_y    0
Relbow_x       0
Relbow_y       0
Rwrist_x       0
RWrist_y       0
LShoulder_x    0
LShoulder_y    0
LElbow_x       0
LElbow_y       0
LWrist_x       0
LWrist_y       0
RHip_x         0
RHip_y         0
RKnee_x        0
RKnee_y        0
RAnkle_x       0
RAnkle_y       0
LHip_x         0
LHip_y         0
LKnee_x        0
LKnee_y        0
LAnkle_x       1
LAnkle_y       1
REye_x         1
REye_y         1
LEye_x         1
LEye_y         1
REar_x         1
REar_y         1
LEar_x         1
LEar_y         1
class          1
dtype: int64

In [106]:
df['LAnkle_x'].unique()

array([0.61111111, 0.61574074, 0.60648148, 0.59722222, 0.60185185,
       0.625     , 0.62037037, 0.64814815, 0.66203704, 0.65740741,
       0.66666667, 0.68518519, 0.63888889, 0.63425926, 0.62962963,
       0.65277778, 0.64351852, 0.76851852, 0.75      , 0.74074074,
       0.71759259, 0.69444444, 0.67592593, 0.55092593, 0.52777778,
       0.51388889, 0.53240741, 0.59259259, 0.6712963 , 0.7037037 ,
       0.71296296, 0.75925926, 0.77314815, 0.77777778, 0.76388889,
       0.75462963, 0.73148148, 0.68981481, 0.5462963 , 0.50462963,
       0.48611111, 0.44907407, 0.43055556, 0.4212963 , 0.43518519,
       0.45833333, 0.52314815, 0.57407407, 0.70833333, 0.78240741,
       0.8287037 , 0.85185185, 0.87037037, 0.79166667, 0.49074074,
       0.54166667, 0.90740741, 0.5787037 , 0.46759259, 0.4537037 ,
       0.56018519, 0.58333333, 0.58796296, 0.56944444, 0.55555556,
       0.56481481, 0.50925926, 0.46296296, 0.42592593, 0.47685185,
       0.68055556, 0.69907407, 0.72222222, 0.72685185, 0.74537

In [107]:
df['LAnkle_x'].value_counts()

0.620370    129
0.629630    114
0.625000     87
0.615741     81
0.587963     75
           ... 
0.689815      1
0.680556      1
0.907407      1
0.425926      1
0.490741      1
Name: LAnkle_x, Length: 85, dtype: int64

In [108]:
df['LAnkle_x'].mode()[0]

0.6203703703703703

In [109]:
df['LAnkle_x']=df['LAnkle_x'].fillna(df['LAnkle_x'].mode()[0])

In [110]:
df['LAnkle_x'].isnull().sum()

0

In [111]:
df['LAnkle_y'].unique()

array([0.75543478, 0.76630435, 0.76086957, 0.75      , 0.73913043,
       0.74456522, 0.73369565, 0.77173913, 0.72282609, 0.77717391,
       0.6576087 , 0.7826087 , 0.78804348, 0.72826087, 0.63586957,
       0.57608696, 0.63043478, 0.67391304, 0.69021739, 0.68478261,
       0.70108696, 0.7173913 , 0.70652174, 0.69565217, 0.71195652,
       0.67934783, 0.61956522, 0.625     , 0.61413043, 0.60869565,
       0.54891304, 0.59782609, 0.64130435, 0.50543478, 0.51086957,
       0.57065217, 0.65217391, 0.64673913, 0.66304348, 0.51630435,
       0.79891304, 0.60326087, 0.55978261, 0.58695652, 0.89130435,
       0.89673913, 0.79347826, 0.80434783, 0.88043478, 0.86413043,
       0.88586957, 0.82608696, 0.875     , 0.90217391, 0.85326087,
       0.80978261, 0.86956522, 0.84782609, 0.82065217, 0.81521739,
       0.83152174, 0.83695652, 0.85869565, 0.8423913 , 0.91304348,
       0.91847826, 0.93478261, 0.9076087 , 0.92391304, 0.95108696,
       0.95652174, 0.96195652, 0.92934783, 0.9673913 , 0.94565

In [112]:
df['LAnkle_y'].value_counts()

0.766304    138
0.760870     90
0.782609     87
0.777174     77
0.750000     69
           ... 
0.559783      1
0.505435      1
0.516304      1
0.603261      1
0.548913      1
Name: LAnkle_y, Length: 77, dtype: int64

In [113]:
df['LAnkle_y'].mode()[0]

0.7663043478260869

In [114]:
df['LAnkle_y']=df['LAnkle_y'].fillna(df['LAnkle_y'].mode()[0])

In [115]:
df['LAnkle_y'].isnull().sum()

0

In [116]:
df['REye_x'].unique()

array([0.62962963, 0.63425926, 0.65740741, 0.65277778, 0.66203704,
       0.6712963 , 0.67592593, 0.68055556, 0.69444444, 0.69907407,
       0.68518519, 0.68981481, 0.66666667, 0.5462963 , 0.54166667,
       0.53240741, 0.53703704, 0.52314815, 0.51851852, 0.51388889,
       0.50925926, 0.50462963, 0.52777778, 0.5       , 0.49537037,
       0.55092593, 0.56481481, 0.57407407, 0.60185185, 0.625     ,
       0.7037037 , 0.70833333, 0.71296296, 0.71759259, 0.72685185,
       0.72222222, 0.55555556, 0.56944444, 0.58333333, 0.59722222,
       0.61111111, 0.63888889, 0.64351852, 0.62037037, 0.5787037 ,
       0.60648148, 0.59259259, 0.58796296, 0.48611111, 0.48148148,
       0.49074074, 0.64814815, 0.61574074, 0.56018519, 0.47685185,
       0.47222222, 0.46759259, 0.45833333, 0.4537037 , 0.44444444,
       0.43981481,        nan])

In [117]:
df['REye_x'].value_counts()

0.546296    81
0.550926    69
0.569444    68
0.555556    64
0.537037    57
            ..
0.453704     2
0.444444     2
0.726852     1
0.717593     1
0.458333     1
Name: REye_x, Length: 61, dtype: int64

In [118]:
df['REye_x'].mode()[0]

0.5462962962962963

In [119]:
df['REye_x']=df['REye_x'].fillna(df['REye_x'].mode()[0])

In [120]:
df['REye_x'].isnull().sum()

0

In [121]:
df['REye_y'].unique()

array([0.14673913, 0.15217391, 0.16304348, 0.1576087 , 0.14130435,
       0.16847826, 0.17934783, 0.17391304, 0.19021739, 0.13586957,
       0.13043478, 0.11413043, 0.11956522, 0.18478261, 0.19565217,
       0.20108696, 0.20652174, 0.21195652, 0.34782609, 0.3423913 ,
       0.32608696, 0.33695652, 0.33152174, 0.32065217, 0.31521739,
       0.30978261, 0.29891304, 0.30434783, 0.35326087, 0.29347826,
       0.125     , 0.10869565, 0.40217391, 0.4076087 , 0.41304348,
       0.41847826, 0.42391304, 0.42934783, 0.43478261, 0.44021739,
       0.44565217, 0.45108696, 0.4673913 , 0.47282609, 0.45652174,
       0.47826087, 0.48369565, 0.48913043, 0.49456522, 0.46195652,
       0.51630435, 0.51086957, 0.5326087 , 0.53804348, 0.52173913,
       0.50543478, 0.5       ,        nan])

In [122]:
df['REye_y'].value_counts()

0.146739    128
0.152174    108
0.141304     92
0.157609     78
0.472826     76
0.331522     73
0.135870     72
0.461957     71
0.336957     56
0.326087     56
0.163043     54
0.467391     52
0.445652     49
0.456522     48
0.478261     46
0.320652     41
0.168478     39
0.451087     38
0.434783     33
0.342391     31
0.440217     29
0.130435     27
0.315217     26
0.489130     26
0.429348     21
0.483696     21
0.173913     20
0.309783     19
0.494565     16
0.201087     13
0.125000     12
0.206522     11
0.418478     10
0.195652     10
0.500000      8
0.190217      7
0.298913      7
0.347826      7
0.179348      6
0.407609      5
0.304348      5
0.505435      4
0.510870      4
0.184783      4
0.402174      3
0.108696      3
0.516304      3
0.353261      2
0.521739      2
0.114130      2
0.423913      2
0.532609      2
0.538043      1
0.413043      1
0.211957      1
0.293478      1
0.119565      1
Name: REye_y, dtype: int64

In [123]:
df['REye_y'].mode()[0]

0.1467391304347826

In [124]:
df['REye_y']=df['REye_y'].fillna(df['REye_y'].mode()[0])

In [125]:
df['REye_y'].isnull().sum()

0

In [126]:
df['LEye_x'].unique()

array([0.65277778, 0.65740741, 0.67592593, 0.68055556, 0.68981481,
       0.69907407, 0.69444444, 0.68518519, 0.7037037 , 0.71759259,
       0.72222222, 0.66666667, 0.6712963 , 0.70833333, 0.71296296,
       0.56944444, 0.56481481, 0.56018519, 0.55092593, 0.55555556,
       0.5462963 , 0.54166667, 0.53240741, 0.52777778, 0.53703704,
       0.52314815, 0.51851852, 0.51388889, 0.58796296, 0.59722222,
       0.625     , 0.64814815, 0.        , 0.72685185, 0.73148148,
       0.73611111, 0.74074074, 0.57407407, 0.58333333, 0.60185185,
       0.61574074, 0.63425926, 0.66203704, 0.64351852, 0.59259259,
       0.62037037, 0.61111111, 0.62962963, 0.60648148, 0.50462963,
       0.5       , 0.50925926, 0.63888889, 0.49537037, 0.49074074,
       0.48611111, 0.48148148, 0.47685185, 0.46759259, 0.46296296,
       0.5787037 ,        nan])

In [127]:
df['LEye_x'].value_counts()

0.574074    78
0.578704    77
0.569444    76
0.587963    65
0.597222    62
            ..
0.476852     2
0.467593     2
0.731481     1
0.486111     1
0.481481     1
Name: LEye_x, Length: 61, dtype: int64

In [128]:
df['LEye_x'].mode()[0]

0.5740740740740741

In [129]:
df['LEye_x']=df['LEye_x'].fillna(df['LEye_x'].mode()[0])

In [130]:
df['LEye_x'].isnull().sum()

0

In [131]:
df['LEye_y'].unique()

array([0.14673913, 0.15217391, 0.16847826, 0.1576087 , 0.16304348,
       0.14130435, 0.17934783, 0.18478261, 0.19021739, 0.13586957,
       0.13043478, 0.17391304, 0.125     , 0.10869565, 0.11413043,
       0.20108696, 0.20652174, 0.21195652, 0.2173913 , 0.        ,
       0.19565217, 0.35326087, 0.34782609, 0.3423913 , 0.33152174,
       0.32608696, 0.33695652, 0.32065217, 0.31521739, 0.30978261,
       0.30434783, 0.29347826, 0.29891304, 0.28804348, 0.11956522,
       0.40217391, 0.4076087 , 0.41847826, 0.42391304, 0.42934783,
       0.43478261, 0.44021739, 0.44565217, 0.45108696, 0.46195652,
       0.4673913 , 0.45652174, 0.47826087, 0.47282609, 0.48369565,
       0.48913043, 0.49456522, 0.52173913, 0.51630435, 0.5326087 ,
       0.53804348, 0.52717391, 0.51086957, 0.50543478, 0.5       ,
              nan])

In [132]:
df['LEye_y'].value_counts()

0.146739    119
0.152174    103
0.141304     88
0.135870     79
0.331522     70
0.456522     67
0.130435     61
0.157609     60
0.467391     56
0.461957     55
0.445652     52
0.336957     51
0.326087     49
0.434783     45
0.451087     44
0.320652     42
0.472826     40
0.000000     38
0.163043     37
0.478261     37
0.168478     36
0.315217     33
0.440217     29
0.342391     28
0.483696     28
0.489130     24
0.429348     20
0.309783     17
0.494565     13
0.304348     13
0.190217     12
0.500000     11
0.418478     11
0.125000     11
0.179348      9
0.211957      8
0.184783      8
0.206522      8
0.298913      7
0.173913      7
0.347826      6
0.402174      6
0.423913      5
0.119565      4
0.201087      4
0.108696      4
0.407609      3
0.195652      3
0.217391      3
0.293478      2
0.353261      2
0.521739      2
0.516304      2
0.538043      2
0.527174      2
0.505435      2
0.114130      2
0.288043      1
0.532609      1
0.510870      1
Name: LEye_y, dtype: int64

In [133]:
df['LEye_y'].mode()[0]

0.1467391304347826

In [134]:
df['LEye_y']=df['LEye_y'].fillna(df['LEye_y'].mode()[0])

In [135]:
df['LEye_y'].isnull().sum()

0

In [136]:
df['REar_x'].unique()

array([0.61574074, 0.61111111, 0.63425926, 0.63888889, 0.64814815,
       0.65740741, 0.66203704, 0.        , 0.66666667, 0.6712963 ,
       0.62037037, 0.625     , 0.65277778, 0.67592593, 0.62962963,
       0.64351852, 0.53240741, 0.52777778, 0.52314815, 0.51388889,
       0.50925926, 0.50462963, 0.5       , 0.49537037, 0.49074074,
       0.48611111, 0.48148148, 0.51851852, 0.5462963 , 0.55555556,
       0.57407407, 0.59722222, 0.60185185, 0.68055556, 0.68518519,
       0.68981481, 0.69444444, 0.69907407, 0.55092593, 0.56481481,
       0.5787037 , 0.60648148, 0.58333333, 0.58796296, 0.59259259,
       0.56018519, 0.56944444, 0.46759259, 0.47222222, 0.47685185,
       0.53703704, 0.54166667, 0.43055556, 0.42592593, 0.43518519,
       0.44907407, 0.4537037 , 0.45833333, 0.46296296,        nan])

In [137]:
df['REar_x'].value_counts()

0.000000    466
0.532407     66
0.550926     46
0.606481     46
0.523148     45
0.601852     44
0.546296     44
0.537037     38
0.569444     37
0.541667     34
0.555556     34
0.527778     33
0.583333     33
0.611111     32
0.587963     31
0.578704     29
0.509259     27
0.574074     27
0.597222     26
0.513889     26
0.518519     24
0.560185     24
0.495370     24
0.490741     24
0.564815     23
0.592593     23
0.615741     20
0.472222     18
0.648148     17
0.657407     17
0.620370     17
0.481481     16
0.662037     14
0.467593     13
0.652778     13
0.504630     12
0.685185     12
0.675926     11
0.671296     10
0.643519     10
0.476852     10
0.634259      9
0.666667      8
0.625000      8
0.486111      7
0.500000      6
0.638889      5
0.680556      4
0.699074      3
0.694444      3
0.425926      3
0.458333      3
0.629630      2
0.689815      1
0.430556      1
0.435185      1
0.449074      1
0.453704      1
0.462963      1
Name: REar_x, dtype: int64

In [138]:
df['REar_x'].mode()[0]

0.0

In [139]:
df['REar_x']=df['REar_x'].fillna(df['REar_x'].mode()[0])

In [140]:
df['REar_x'].isnull().sum()

0

In [141]:
df.isnull().sum()

nose_x         0
nose_y         0
neck_x         0
neck_y         0
Rshoulder_x    0
Rshoulder_y    0
Relbow_x       0
Relbow_y       0
Rwrist_x       0
RWrist_y       0
LShoulder_x    0
LShoulder_y    0
LElbow_x       0
LElbow_y       0
LWrist_x       0
LWrist_y       0
RHip_x         0
RHip_y         0
RKnee_x        0
RKnee_y        0
RAnkle_x       0
RAnkle_y       0
LHip_x         0
LHip_y         0
LKnee_x        0
LKnee_y        0
LAnkle_x       0
LAnkle_y       0
REye_x         0
REye_y         0
LEye_x         0
LEye_y         0
REar_x         0
REar_y         1
LEar_x         1
LEar_y         1
class          1
dtype: int64

In [142]:
df['REar_y'].unique()

array([0.1576087 , 0.15217391, 0.16304348, 0.16847826, 0.14673913,
       0.        , 0.17391304, 0.17934783, 0.18478261, 0.14130435,
       0.13586957, 0.13043478, 0.19021739, 0.19565217, 0.20108696,
       0.3423913 , 0.32608696, 0.33695652, 0.33152174, 0.32065217,
       0.31521739, 0.34782609, 0.30978261, 0.30434783, 0.29891304,
       0.125     , 0.11956522, 0.4076087 , 0.41304348, 0.41847826,
       0.42391304, 0.42934783, 0.43478261, 0.44021739, 0.44565217,
       0.46195652, 0.45108696, 0.4673913 , 0.47282609, 0.45652174,
       0.48369565, 0.48913043, 0.51086957, 0.51630435, 0.50543478,
       0.47826087, 0.49456522, 0.5       ,        nan])

In [143]:
df['REar_y'].value_counts()

0.000000    466
0.157609    105
0.461957     75
0.163043     74
0.152174     67
0.467391     61
0.146739     60
0.472826     55
0.456522     51
0.336957     47
0.326087     39
0.451087     38
0.320652     35
0.331522     34
0.168478     33
0.179348     28
0.429348     26
0.434783     26
0.440217     24
0.141304     23
0.315217     23
0.445652     22
0.173913     20
0.342391     17
0.478261     15
0.184783     12
0.135870     12
0.190217     11
0.423913     11
0.195652      9
0.309783      8
0.483696      7
0.347826      7
0.413043      6
0.494565      6
0.130435      6
0.489130      5
0.304348      4
0.119565      3
0.505435      2
0.500000      2
0.418478      2
0.510870      1
0.516304      1
0.407609      1
0.125000      1
0.201087      1
0.298913      1
Name: REar_y, dtype: int64

In [144]:
df['REar_y'].mode()[0]

0.0

In [145]:
df['REar_y']=df['REar_y'].fillna(df['REar_y'].mode()[0])

In [146]:
df['REar_y'].isnull().sum()

0

In [147]:
df['LEar_x'].unique()

array([0.66666667, 0.6712963 , 0.66203704, 0.        , 0.68518519,
       0.68981481, 0.69907407, 0.70833333, 0.71759259, 0.72222222,
       0.71296296, 0.7037037 , 0.72685185, 0.73611111, 0.73148148,
       0.58333333, 0.5787037 , 0.58796296, 0.59259259, 0.57407407,
       0.56481481, 0.55555556, 0.55092593, 0.5462963 , 0.54166667,
       0.53703704, 0.56018519, 0.56944444, 0.60185185, 0.61574074,
       0.63888889, 0.74074074, 0.74537037, 0.60648148, 0.61111111,
       0.62037037, 0.62962963, 0.63425926, 0.69444444, 0.67592593,
       0.625     , 0.64351852, 0.64814815, 0.51851852, 0.52314815,
       0.52777778, 0.53240741, 0.51388889, 0.50925926, 0.68055556,
       0.65740741, 0.59722222, 0.50462963, 0.49537037, 0.48611111,
       0.48148148, 0.49074074, 0.65277778,        nan])

In [148]:
df['LEar_x'].value_counts()

0.000000    326
0.601852     74
0.606481     71
0.597222     71
0.615741     59
0.634259     52
0.583333     48
0.578704     44
0.592593     43
0.611111     41
0.625000     40
0.587963     36
0.574074     34
0.564815     34
0.620370     33
0.629630     32
0.560185     31
0.541667     29
0.638889     29
0.643519     29
0.569444     27
0.652778     27
0.666667     24
0.662037     24
0.671296     23
0.657407     22
0.648148     21
0.555556     20
0.546296     20
0.550926     18
0.675926     16
0.537037     16
0.518519     15
0.523148     14
0.527778     14
0.726852     12
0.680556     11
0.685185      9
0.689815      9
0.717593      9
0.708333      8
0.722222      8
0.532407      8
0.694444      7
0.736111      7
0.731481      7
0.712963      6
0.699074      5
0.703704      5
0.486111      3
0.509259      3
0.740741      2
0.504630      2
0.513889      1
0.745370      1
0.495370      1
0.481481      1
0.490741      1
Name: LEar_x, dtype: int64

In [149]:
df['LEar_x'].mode()[0]

0.0

In [150]:
df['LEar_x']=df['LEar_x'].fillna(df['LEar_x'].mode()[0])

In [151]:
df['LEar_x'].isnull().sum()

0

In [152]:
df['LEar_y'].unique()

array([0.15217391, 0.1576087 , 0.        , 0.16847826, 0.16304348,
       0.14130435, 0.19565217, 0.19021739, 0.17391304, 0.13586957,
       0.14673913, 0.13043478, 0.11413043, 0.11956522, 0.20108696,
       0.20652174, 0.21195652, 0.2173913 , 0.22282609, 0.18478261,
       0.17934783, 0.35326087, 0.34782609, 0.33152174, 0.32608696,
       0.33695652, 0.3423913 , 0.32065217, 0.31521739, 0.30978261,
       0.29891304, 0.30434783, 0.29347826, 0.125     , 0.40217391,
       0.4076087 , 0.41304348, 0.41847826, 0.42391304, 0.42934783,
       0.43478261, 0.44021739, 0.45108696, 0.44565217, 0.46195652,
       0.4673913 , 0.47282609, 0.47826087, 0.48369565, 0.5       ,
       0.50543478, 0.49456522, 0.51086957, 0.51630435, 0.48913043,
       0.45652174,        nan])

In [153]:
df['LEar_y'].value_counts()

0.000000    326
0.152174    108
0.146739     98
0.157609     93
0.451087     79
0.141304     76
0.456522     70
0.445652     63
0.461957     55
0.467391     54
0.135870     51
0.320652     47
0.336957     41
0.331522     39
0.326087     38
0.163043     28
0.168478     26
0.440217     26
0.429348     25
0.472826     24
0.315217     21
0.309783     20
0.418478     17
0.173913     17
0.423913     16
0.478261     15
0.434783     11
0.130435      9
0.342391      9
0.304348      8
0.211957      7
0.489130      7
0.298913      5
0.402174      4
0.407609      4
0.114130      4
0.347826      4
0.179348      4
0.483696      3
0.206522      3
0.293478      3
0.201087      2
0.119565      2
0.195652      2
0.125000      2
0.500000      2
0.505435      2
0.494565      2
0.510870      2
0.516304      2
0.190217      2
0.222826      1
0.217391      1
0.184783      1
0.353261      1
0.413043      1
Name: LEar_y, dtype: int64

In [157]:
df['LEar_y'].mode()[0]

0.0

In [158]:
df['LEar_y']=df['LEar_y'].fillna(df['LEar_y'].mode()[0])

In [156]:
df['LEar_y'].isnull().sum()

0

In [159]:
df['class'].unique()

array(['kick', 'punch', 'squat', 'stand', nan], dtype=object)

In [160]:
df['class'].value_counts()

squat    571
kick     525
punch    438
stand     49
Name: class, dtype: int64

In [161]:
df['class'].mode()[0]

'squat'

In [162]:
df['class']=df['class'].fillna(df['class'].mode()[0])

In [163]:
df['class'].isnull().sum()

0

In [164]:
df.isnull().sum()

nose_x         0
nose_y         0
neck_x         0
neck_y         0
Rshoulder_x    0
Rshoulder_y    0
Relbow_x       0
Relbow_y       0
Rwrist_x       0
RWrist_y       0
LShoulder_x    0
LShoulder_y    0
LElbow_x       0
LElbow_y       0
LWrist_x       0
LWrist_y       0
RHip_x         0
RHip_y         0
RKnee_x        0
RKnee_y        0
RAnkle_x       0
RAnkle_y       0
LHip_x         0
LHip_y         0
LKnee_x        0
LKnee_y        0
LAnkle_x       0
LAnkle_y       0
REye_x         0
REye_y         0
LEye_x         0
LEye_y         0
REar_x         0
REar_y         0
LEar_x         0
LEar_y         0
class          0
dtype: int64

In [165]:
df['class'].value_counts()

squat    572
kick     525
punch    438
stand     49
Name: class, dtype: int64